{"name": "test_division_03", "status": "passed", "description": "pytest.xfail在用例内部跳过用例的测试用例", "start": 1566229383532, "stop": 1566229383532, "uuid": "7a244a59-8593-497d-bdb3-63da4c41e91b", "historyId": "2695f6872ab747bc6fb57fbc56b6f8ed", "fullName": "mytestcase.test_division.test_division01#test_division_03", "labels": [{"name": "parentSuite", "value": "mytestcase.test_division"}, {"name": "suite", "value": "test_division01"}, {"name": "subSuite"}, {"name": "host", "value": "YouTh"}, {"name": "thread", "value": "5544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "mytestcase.test_division.test_division01"}]}